name: CI

on: [push]

jobs:
  check:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: dschep/install-pipenv-action@v1

      - run: pipenv install

      - run: python -m doctest -v services/Crypto.py