name: Docker Latest build

on:
  push:
    branches:
      - master

jobs:
  check:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - uses: dschep/install-pipenv-action@v1

      - run: pipenv lock -r > requirements.txt
      - run: pip install -r requirements.txt

      - run: python -m doctest -v services/Crypto.py
  publish:
    needs: check
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Release Version
        # use latest tag as release version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_SHA}

      - name: Build docker image, push
        uses: docker/build-push-action@v1
        with:
          repository: lukaswire/swa-user-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # pass release_version
          build_args: release_version=${{ env.RELEASE_VERSION }}
          # tag the image with name of the branch - latest as this is master
          tag_with_ref: true
          # add labels based on the build - see https://github.com/opencontainers/image-spec/blob/master/annotations.md
          add_git_labels: true
          # push
          push: true