name: Release Pipeline

on:
  release:
    types: published

jobs:
  check:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: dschep/install-pipenv-action@v1

      - run: pipenv install

      - run: python -m doctest -v services/Crypto.py

  deploy:
    needs: check
    name: Build and deploy service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Release Version
        # use latest tag as release version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}

      - name: Build and publish docker image
        uses: docker/build-push-action@v1
        with:
          repository: lukaswire/swa-user-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # pass release_version
          build_args: release_version=${{ env.RELEASE_VERSION }}
          # tag the image with latest git tag
          tag_with_ref: true
          # add labels based on the build - see https://github.com/opencontainers/image-spec/blob/master/annotations.md
          add_git_labels: true
          # push only if this is tagged release
          push: ${{ startsWith(github.ref, 'refs/tags/') }}

